/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/Models/Fish.gltf -t -r public 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import {Euler, Vector3} from 'three'
import {MeshProps} from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Plane: THREE.Mesh
    Plane001: THREE.Mesh
    Plane002: THREE.Mesh
    Plane003: THREE.Mesh
    Plane004: THREE.Mesh
    Plane005: THREE.Mesh
    Sphere: THREE.Mesh
    Sphere001: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshPhysicalMaterial
    ['Material.001']: THREE.MeshPhysicalMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
}

type FishProps = JSX.IntrinsicElements['group'] & {
    pushRef?: (ref: any) => void,
    velocity: Vector3,
    position?: Vector3,
    acc?: Vector3,
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function FishModel(props: FishProps) {
  const { nodes, materials } = useGLTF('/Models/Fish.gltf') as GLTFResult
  return (
    <group {...props} 
           
           dispose={null}
           ref={(ref)=>{
               if(ref && props.pushRef){
                   props.pushRef(ref)
               }
           }}
    >
      <mesh rotation={new Euler( Math.PI/2, 0, 0, 'XYZ' )}  geometry={nodes.Cube.geometry} material={materials['Material.002']} />
      <mesh rotation={new Euler( Math.PI/2, 0, 0, 'XYZ' )}  geometry={nodes.Plane.geometry} material={materials['Material.002']} />
      <mesh rotation={new Euler( Math.PI/2, 0, 0, 'XYZ' )}  geometry={nodes.Plane001.geometry} material={materials['Material.001']} />
      <mesh rotation={new Euler( Math.PI/2, 0, 0, 'XYZ' )}  geometry={nodes.Plane002.geometry} material={materials['Material.001']} />
      <mesh rotation={new Euler( Math.PI/2, 0, 0, 'XYZ' )}  geometry={nodes.Plane003.geometry} material={materials['Material.001']} />
      <mesh rotation={new Euler( Math.PI/2, 0, 0, 'XYZ' )}  geometry={nodes.Plane004.geometry} material={materials['Material.001']} />
      <mesh rotation={new Euler( Math.PI/2, 0, 0, 'XYZ' )}  geometry={nodes.Plane005.geometry} material={materials['Material.001']} />
      <mesh rotation={new Euler( Math.PI/2, 0, 0, 'XYZ' )}  geometry={nodes.Sphere.geometry} material={materials['Material.003']} />
      <mesh rotation={new Euler( Math.PI/2, 0, 0, 'XYZ' )}  geometry={nodes.Sphere001.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/Models/Fish.gltf')
